name: module_5_ci

on:
  push:
    paths:
      - "module_5/**"
      - ".github/workflows/module_5_ci.yml"
  pull_request:
    paths:
      - "module_5/**"
      - ".github/workflows/module_5_ci.yml"

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: module_5

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gradcafe
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d gradcafe"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20

    env:
      # Force app/tests to use the least-privilege user in CI
      DATABASE_URL: postgresql://app_user:app_user_ci_password@localhost:5432/gradcafe

      # Also set PG* in case any code/tests use these instead of DATABASE_URL
      PGHOST: localhost
      PGPORT: 5432
      PGDATABASE: gradcafe
      PGUSER: app_user
      PGPASSWORD: app_user_ci_password

      FLASK_SECRET_KEY: ci_dummy_secret_key

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: System deps (graphviz + psql)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y graphviz postgresql-client

      - name: Install Python deps (module_5)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- DB setup: create schema/table as postgres, then create least-priv user + grants ---
      - name: Initialize DB schema + create least-privilege user
        env:
          # Force schema init to run as postgres (not app_user)
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/gradcafe
          PGUSER: postgres
          PGPASSWORD: postgres
        run: |
          # Create tables/indexes/etc (your script)
          python -m src.load_data || true

          # Create least-priv user + grant only what app needs
          psql "postgresql://postgres:postgres@localhost:5432/gradcafe" -v ON_ERROR_STOP=1 <<'SQL'
          DO $$
          BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_user') THEN
              CREATE ROLE app_user LOGIN PASSWORD 'app_user_ci_password';
            END IF;
          END
          $$;

          GRANT CONNECT ON DATABASE gradcafe TO app_user;
          GRANT USAGE ON SCHEMA public TO app_user;

          -- Prevent INSERT errors during tests/pipeline: allow INSERT on applicants
          GRANT SELECT, INSERT ON TABLE public.applicants TO app_user;
          SQL

      # 1) Pylint (fail under 10)
      - name: Run pylint (fail under 10)
        run: |
          pylint src tests --fail-under=10

      # 2) Pytest
      - name: Run pytest
        run: |
          pytest -m "web or buttons or analysis or db or integration"

      # 3) dependency.svg via pydeps + graphviz
      - name: Generate dependency.svg
        run: |
          pydeps src/app.py --noshow -T svg -o dependency.svg
          test -f dependency.svg

      # 4) snyk test (dependency scan) - do not hard fail if token missing
      - name: Install Snyk CLI
        run: |
          npm install -g snyk

      - name: Run snyk test (deps)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          if [ -n "$SNYK_TOKEN" ]; then
            snyk auth "$SNYK_TOKEN"
            snyk test || true
          else
            echo "SNYK_TOKEN not set in GitHub Secrets; skipping snyk test."
          fi

      # Extra credit: Snyk Code (SAST)
      - name: Run snyk code test (SAST)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          if [ -n "$SNYK_TOKEN" ]; then
            snyk code test || true
          else
            echo "SNYK_TOKEN not set in GitHub Secrets; skipping snyk code test."
          fi