name: module_5_ci

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: module_5

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gradcafe
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d gradcafe"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: gradcafe
      DB_USER: postgres
      DB_PASSWORD: postgres
      FLASK_SECRET_KEY: ci_dummy_secret_key

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Initialize database schema
        run: |
          python -m src.load_data || true

      - name: Run pylint (fail under 10)
        run: |
          pylint src tests --fail-under=10

      - name: Run pytest
        run: |
          pytest -m "web or buttons or analysis or db or integration"

      - name: Generate dependency.svg
        run: |
          pydeps src/app.py --noshow -T svg -o dependency.svg
          test -f dependency.svg

      - name: Run snyk test (do not fail build)
        run: |
          snyk test || true
